Feature: Shop # features/features/Shop2/Shop4.feature:1

  Scenario: User can navigate to Shop page                                # features/features/Shop2/Shop4.feature:3
    Given I have navigated to the main page                               # common/given.py:12
    When I click on the SHOP2 button                                      # features/steps/Shop2/Shop2.py:13
      Traceback (most recent call last):
        File "c:\users\mbcx6ag2\appdata\local\programs\python\python37-32\lib\site-packages\behave\model.py", line 1329, in run
          match.run(runner.context)
        File "c:\users\mbcx6ag2\appdata\local\programs\python\python37-32\lib\site-packages\behave\matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "C:\01\features\steps\Shop2\Shop2.py", line 16, in i_click_dresses_button
          findXP(context, e["SHOP_button"]).click()
        File "c:\users\mbcx6ag2\appdata\local\programs\python\python37-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
          self._execute(Command.CLICK_ELEMENT)
        File "c:\users\mbcx6ag2\appdata\local\programs\python\python37-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 628, in _execute
          return self._parent.execute(command, params)
        File "c:\users\mbcx6ag2\appdata\local\programs\python\python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 318, in execute
          response = self.command_executor.execute(driver_command, params)
        File "c:\users\mbcx6ag2\appdata\local\programs\python\python37-32\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 472, in execute
          return self._request(command_info[0], url, body=data)
        File "c:\users\mbcx6ag2\appdata\local\programs\python\python37-32\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 496, in _request
          resp = self._conn.getresponse()
        File "c:\users\mbcx6ag2\appdata\local\programs\python\python37-32\lib\http\client.py", line 1321, in getresponse
          response.begin()
        File "c:\users\mbcx6ag2\appdata\local\programs\python\python37-32\lib\http\client.py", line 296, in begin
          version, status, reason = self._read_status()
        File "c:\users\mbcx6ag2\appdata\local\programs\python\python37-32\lib\http\client.py", line 257, in _read_status
          line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
        File "c:\users\mbcx6ag2\appdata\local\programs\python\python37-32\lib\socket.py", line 589, in readinto
          return self._sock.recv_into(b)
      ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

    Then The page titled "Products – Automation Practice Site" has loaded # None


Failing scenarios:
  features/features/Shop2/Shop4.feature:3  User can navigate to Shop page

0 features passed, 1 failed, 0 skipped
0 scenarios passed, 1 failed, 0 skipped
1 step passed, 1 failed, 1 skipped, 0 undefined
Took 1m10.204s
